apiVersion: apps/v1
kind: Deployment
metadata:
 name: bar-deployment
spec:
 replicas: 3
 minReadySeconds: 5
 selector:
  matchLabels:
   app: bar-demo
 strategy:
  rollingUpdate:
   maxSurge: 1
   maxUnavailable: 0
  type: RollingUpdate
 template:
  metadata:
   name: bar-app
   labels:
    app: bar-demo
  spec:
   containers:
    - image: 444716303806.dkr.ecr.ap-northeast-2.amazonaws.com/eks-demo:latest
      name: eks-demo
      env:
       - name: SERVICE_NAME
         valueFrom:
          configMapKeyRef:
           name: bar-cm
           key: service-name
      command: ["/bin/sh","-c", "java -jar -Dservice.name=$(SERVICE_NAME) eks-demo.jar"]
      readinessProbe:
       periodSeconds: 1
       httpGet:
        path: /hello
        port: 9090