apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-demo
  labels:
    app: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: eks-demo
        image: "{url}/{image}:{tag}"
        ports:
        - containerPort: 8080