apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-demo
  labels:
    app: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: eks-demo
        env:
          - name: REGISTRY_URL
            valueFrom: 
              congifMapKeyRef:
                name: demo-config
                key: url
          - name: IMAGE_NAME
            valueFrom: 
              congifMapKeyRef:
                name: demo-config
                key: image
          - name: TAG
            valueFrom: 
              congifMapKeyRef:
                name: demo-config
                key: tagTAG
        image: $(REGISTRY_URL):$(IMAGE_NAME):$(TAG)
        ports:
        - containerPort: 8080