pipeline {
    stage('Deploy to Kubernetes') {
        steps {
            script {
                kubernetesDeploy(configs: "eks-demo-deployment.yml", kubeconfigId: "my-kubeconfig")
            }
        }
    }
}